### PR TITLE
WIP adding BlueMicro 52840 to boards

### PR DESCRIPTION
**Pull request by jpconstantineau**
Preparing a pull request for your comments and suggestions.  
I still need to fully test it out within the IDE and with the bootloader (also PR'ed).

VID and PID have been handed out by openmoko in this [PR](https://github.com/openmoko/openmoko-usb-oui/pull/20).

We will need to add the bootloader binaries once the PR on the bootloader repo is approved.

Let me know if there is any specific requirements on "third party boards" you may have for pulling them into this repo.

### CODE REVIEW

**Comment by hathach** [comment]
can fork and create their own board support package - we dont manufacture it so we wouldn't be able to add support. thanks :)

**Comment by jpconstantineau** [comment]
Thanks for the comments.
Do you have any recommendations on how to manage a fork and keep in sync with the main BSP?

**Comment by hathach** [comment]
it is up to you for when you think it is to do the sync, good idea to have it sync up on release.

**Comment by jpconstantineau** [comment]
Sync on release is what I had in mind but it wasn't quite what I was really thinking about.   We don't really want to have 2 BSPs with adafruit boards, one official, the other forked with more boards in.  Is there a way to have a "Community BSP" that extends the main BSP?  This way, there is a clear separation while minimizing duplication.  If you know of documentation or a set of BSP that implements this, let me know...

**Comment by ladyada** [comment]
hihi we can't have a BSP from adafruit with boards we dont own or test - we have tried it before and it just ends up with everyone frustrated. its pretty common for folks to fork our BSP and add their boards, here's one that forks our samd51 core
https://learn.sparkfun.com/tutorials/samd51-thing-plus-hookup-guide/setting-up-the-arduino-ide

**Pull request closed without merging**
