### PR TITLE
finished image upload feature

### PR DESCRIPTION
**Pull request by hathach**
- speed is test reliably around 80 KB/s with `write without response` 
- add Bleuart overflowed callback
- improve ada callback, automatically resize queue depth when needed

### CODE REVIEW

**Comment by hathach** [comment]
note: nrf52832 still struggle with memory issue, trying to fix that asap.

**Comment by ladyada** [comment]
ok, if '832 cannot be supported its ok :)

**Comment by hathach** [comment]
@ladyada It got choked up somewhere, while receiving and cause a reset. Possibly another overflow cases somewhere. I am hoping it is not from SD, doing more analyzing tomorrow.

**Comment by hathach** [comment]
somehow sd stack on nrf52832 is written when transferring image. It seems to the cause for 832, analyzing .....
 
```
| Name | Addr 0x2000xxxx | Usage               |
| ---------------------------------------------|
| Stack| 0xF400 - 0xFFFF |  3072 /  3072 (100%) |
| Heap | 0x57B8 - 0xF3FF | 27396 / 40008 (68%) |
| Bss  | 0x3400 - 0x57B7 | 9144                |
| SD   | 0x0000 - 0x33FF | 13312               |
|______________________________________________|
```

**Comment by hathach** [comment]
heap is overflowed on nrf52832 since it doens't have enough memory to handle all the packet from mobile app. Worse, the nano newlib doesn't has any way to report this (making malloc failed). Added `_sbrk()` hook to control the heap growing. And use non-deferred callback for 832. This reduce the memory usage, but also the throughput.

**Comment by ladyada** [comment]
ok!

**Pull request merged**
