### PR TITLE
Add support to ublox Nina B302

### PR DESCRIPTION
**Pull request by ksfreitas**

### CODE REVIEW

**Comment by danilodene** [comment]
Great contribution, thanks

**Comment by hathach** [comment]
sorry, but since we don't make or have these boards and wouldn't be able to maintain or support this board. It is probably better for you to keep a fork and support it.

**Comment by ksfreitas** [comment]
Thanks for reply. I created the custom board for NINA B302 in the repository based on this project: https://github.com/ksfreitas/adafruit-ublox-nrf52-arduino

**Comment by lyusupov** [comment]
@ksfreitas :

https://github.com/jpconstantineau/Community_nRF52_Arduino

**Pull request closed without merging**
